name: ktusch-sync-controller-ui deploy

on:
  push:
    branches: [ master ]


jobs:
  deploy-to-remote-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build Docker Image
        run: |
          docker build --tag ktusch-sync-controller:${{ github.run_number }} .

      - name: Save docker image to .tar
        run: |
          docker save --output=ktusch-sync-controller:${{ github.run_number }}.tar ktusch-sync-controller:${{ github.run_number }}

      - name: Copy .tar Image to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: root
          key: ${{ secrets.PRIVATE_KEY }}
          source: "ktusch-sync-controller:${{ github.run_number }}.tar"
          target: "~/"

      - name: Load and run Docker Image
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: root
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            cd ~
            docker load --input=ktusch-sync-controller:${{ github.run_number }}.tar
            rm -f ktusch-sync-controller:${{ github.run_number }}.tar
            docker rm -f ktusch-sync-controller || true
            docker run -d --network=ktusch-sync-net -p 80:80 --name ktusch-sync-controller ktusch-sync-controller:${{ github.run_number }}
